### ISSUE TITLE
jq: Unknown option --args

### ISSUE THREAD

**Issue by TeddyDD** [alexherbo2/yank-ring.kak#3]
In fzf preview panel:
```
jq: Unknown option --args                                                                 │
│ Use jq --help for help with command-line options,                                         │
│ or see the jq manpage, or online docs  at https://stedolan.github.io/jq 
```
jq --version (Ubuntu 18.04 repo)                                                                                                                                                              
jq-1.5-1-a5b5cbe

**Comment by alexherbo2** [comment]
Your `jq` is not up-to-date enough.

```
--args
    Remaining arguments are positional string arguments.
    These are available to the jq program as `$ARGS.positional[]`.
```

https://stedolan.github.io/jq/manual/

**Comment by TeddyDD** [comment]
As I thought. Thanks.
