### ISSUE TITLE
Will there be a port of the plugin to kakoune.cr

### ISSUE THREAD

**Issue by eko234** [alexherbo2/yank-ring.kak#5]
Hi, I'm using some plugins of yours that depends on kakoune.cr, i would like to use this plugin but the namespaces of connect.kak cause conflicts with kakoune.cr, so I would like to know if you are planning to port yank-ring, thanks :)

**Comment by alexherbo2** [comment]
Yes I will >:)

**Comment by eko234** [comment]
:V cool, hope to use it soon.
